version: "3.7"

services:
  postgres:
    container_name: api_golang_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: api_golang_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/api_golang
    volumes:
       - api_golang:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  api_golang:
    build:
      context: .
      dockerfile: .dockerfile
    image: api_golang
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  api_golang: